package wah

var isDebug bool = false
var isFirstDetect = true
var hasRandomImport = false
var hasTimeImport = false
var inFuncDecl = false
var hasProbGotGlobal = false

type CCW int

const (
	MAP_STRUCTURE_ITER = iota + 1
	RANDOM_NUMBER_GENERATION
	GF_DECLARATION//
	UNCHECKED_INPUT_ARGUMENTS//
	UNHANDLED_ERROR
	USED_GOROUTINE
	PHANTOM_READS
	READ_YOUR_WRITE//
	RANGE_QUERY_RISK//
	USE_TIME_MODULE

	USED_GLOBAL_VARIABLE//1
	USED_CONCURRENCY//2
	CALL_WEB_SERVICE//3
	EXTERNAL_FILE_ACCESS//4
)

// RANGE_QUERY_RISK

func (c CCW) String() string {
	return [...]string{"MAP_STRUCTURE_ITER", "RANDOM_NUMBER_GENERATION", "GF_DECLARATION", 
					   "UNCHECKED_INPUT_ARGUMENTS", "UNHANDLED_ERROR", "USED_GOROUTINE",
					   "PHANTOM_READS", "READ_YOUR_WRITE", "RANGE_QUERY_RISK", "USE_TIME_MODULE", 
					   "USED_GLOBAL_VARIABLE"}[c-1]
}
