name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set env
      run : echo "Set env"
    - name: move backend
      run : cd backend
    - name: Login Dockerhub
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOKCERHUB_USERNAME }} --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag vaporsiriz/bloackchain_staticanalysis
    - name: Push the docker image
      run: docker push vaporsiriz/bloackchain_staticanalysis
